- id: '1638400101028'
  alias: Doorbell
  description: ''
  triggers:
  - event_type: unifiprotect_doorbell
    event_data: {}
    trigger: event
  conditions: []
  actions:
  - data:
      message: Someone is at the {{ area_name(trigger.entity_id) }} door
      entity_id: media_player.kitchen_display
    action: tts.google_translate_say
  mode: single
- id: '1640903808419'
  alias: Back Door Turn Light Off When No More Motion
  description: If the back door lights were turned on by the automation, but motion
    is no longer detected, turn them off
  trigger:
  - platform: state
    entity_id:
    - sensor.back_door_kent_st_detected_object
    to: none
    for:
      hours: 0
      minutes: 0
      seconds: 20
  condition:
  - condition: device
    type: is_on
    device_id: e8c5693dee8c4e27766a8d5a693cc993
    entity_id: light.back_stairs_back_porch_lights_2
    domain: light
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.backdoor_on_by_motion
      state: 'on'
  action:
  - type: turn_off
    device_id: e8c5693dee8c4e27766a8d5a693cc993
    entity_id: light.back_stairs_back_porch_lights_2
    domain: light
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.backdoor_on_by_motion
  mode: single
- id: '1733255266242'
  alias: Remind when clothes in washing machine
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.washing_machine_status
    to: Program ended
    for:
      hours: 0
      minutes: 20
      seconds: 0
    from:
  conditions:
  - type: is_not_open
    condition: device
    device_id: e9bd4b0570a5fb7d87d74d2fa13f8ccd
    entity_id: 8a67600394b4e9729f91f304fe735cee
    domain: binary_sensor
  actions:
  - action: tts.google_translate_say
    metadata: {}
    data:
      entity_id: media_player.kitchen_display
      message: Clothes are still in the washing machine
  mode: single
- id: '1733255396983'
  alias: Remind when clothes in dryer
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.tumble_dryer_status
    to: Finished
    for:
      hours: 0
      minutes: 20
      seconds: 0
    from:
  conditions:
  - type: is_not_open
    condition: device
    device_id: 5c5cf8ddfedaa6143e2a099703d74d54
    entity_id: f9b910e9f4201847e993b59f78b3388b
    domain: binary_sensor
  actions:
  - action: tts.google_translate_say
    metadata: {}
    data:
      entity_id: media_player.kitchen_display
      message: Clothes are still in the dryer
  mode: single
