- alias: Announce printer complete
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - sensor.mfc_j1170dw_status
      from: printing
      to: null
  conditions: []
  actions:
    - action: tts.speak
      metadata: {}
      data:
        cache: true
        media_player_entity_id: media_player.kitchen_display
        message: Printer is done
  mode: single
