- alias: Announce printer complete
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - sensor.mfc_j1170dw_status
      from: printing
      to: null
  conditions: []
  actions:
    - action: tts.google_translate_say
      data:
        message: Printer finished printing
        entity_id: media_player.kitchen_display
  mode: single
