name: Check HASS Configuration

on: 
  push:
  pull_request:
  
jobs:
  hass-config-check: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check HASS Config
        uses: frenck/action-home-assistant@v1
        with:
          path: .
          secrets: secrets.example.yaml
          version: stable
